language: cpp

env:
  global:
    ITK_URL=https://github.com/InsightSoftwareConsortium/ITK
    ITK_SOURCE_DIR=${HOME}/ITK-source
    ITK_BUILD_DIR=${HOME}/ITK-build
    ELASTIX_URL=https://github.com/SuperElastix/elastix
    ELASTIX_SOURCE_DIR=${HOME}/Elastix-source
    ELASTIX_BUILD_DIR=${HOME}/Elastix-build
    NIFTYREG_URL=https://cmiclab.cs.ucl.ac.uk/mmodat/niftyreg.git
    NIFTYREG_SOURCE_DIR=${HOME}/Niftyreg-source
    NIFTYREG_BUILD_DIR=${HOME}/Niftyreg-build
    SUPERELASTIX_SOURCE_DIR=${TRAVIS_BUILD_DIR}/SuperBuild
    SUPERELASTIX_BUILD_DIR=${HOME}/SuperElastix-build
    OMP_NUM_THREADS=2

cache:
  directories:
    - ExternalData_OBJECT_STORES=${HOME}/.ExternalData
    - ${ITK_SOURCE_DIR}
    - ${ITK_BUILD_DIR}
    - ${ELASTIX_SOURCE_DIR}
    - ${ELASTIX_BUILD_DIR}
    - ${NIFTYREG_SOURCE_DIR}
    - ${NIFTYREG_BUILD_DIR}
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_script:
  - mkdir -p ${SUPERELASTIX_BUILD_DIR}

script:
  - if [[ ! -e ${ITK_BUILD_DIR}/ITKConfig.cmake ]]; then
      rm -rf ${ITK_SOURCE_DIR} {ITK_BUILD_DIR} &&
      git clone ${ITK_URL} ${ITK_SOURCE_DIR} &&
      cd ${ITK_SOURCE_DIR} &&
      git checkout v4.11.1 &&
      mkdir -p ${ITK_BUILD_DIR} &&
      cd ${ITK_BUILD_DIR} &&
      cmake -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON -DCMAKE_VISIBILITY_INLINES_HIDDEN:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_SKIP_RPATH:BOOL=ON -DITK_LEGACY_REMOVE:BOOL=ON -DITK_USE_KWSTYLE:BOOL=OFF -DITK_BUILD_DEFAULT_MODULES:BOOL=ON -DModule_ITKReview:BOOL=ON ${ITK_SOURCE_DIR} &&
      make --jobs=4; fi
  - if [[ ! -e ${ELASTIX_BUILD_DIR}/src/UseElastix.cmake ]]; then
      rm -rf ${ELASTIX_SOURCE_DIR} ${ELASTIX_BUILD_DIR} &&
      git clone ${ELASTIX_URL} ${ELASTIX_SOURCE_DIR} &&
      cd ${ELASTIX_SOURCE_DIR} &&
      git checkout ef057ff89233822b26b04b31c3c043af57d5deff &&
      mkdir -p ${ELASTIX_BUILD_DIR} &&
      cd ${ELASTIX_BUILD_DIR} &&
      cmake -DBUILD_TESTING:BOOL=OFF -DELASTIX_BUILD_EXECUTABLE:BOOL=OFF -DITK_DIR=${ITK_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release ${ELASTIX_SOURCE_DIR} &&
      make --jobs=4; fi
  - if [[ ! -e ${NIFTYREG_BUILD_DIR}/reg-apps/reg_adalin ]]; then
      rm -rf ${NIFTYREG_SOURCE_DIR} {NIFTYREG_BUILD_DIR} &&
      git clone -c http.sslVerify=false ${NIFTYREG_URL} ${NIFTYREG_SOURCE_DIR} &&
      cd ${NIFTYREG_SOURCE_DIR} &&
      git checkout 88b369becb6bdbda22ea96a0bef2b83bee85b219 &&
      mkdir -p ${NIFTYREG_BUILD_DIR} &&
      cd ${NIFTYREG_BUILD_DIR} &&
      cmake -DBUILD_ALL_DEP:BOOL=ON -DCMAKE_BUILD_TYPE=Release ${NIFTYREG_SOURCE_DIR} &&
      make --jobs=4 &&
      touch ${HOME_DIR}/built_cache; fi
  - cd ${SUPERELASTIX_BUILD_DIR}
  - if [[ ! -e ${HOME_DIR}/built_cache ]]; then
      cmake -DUSE_SYSTEM_ITK:BOOL=ON -DITK_DIR=${ITK_BUILD_DIR} -DUSE_SYSTEM_ELASTIX:BOOL=ON -DELASTIX_USE_FILE=${ELASTIX_BUILD_DIR}/src/UseElastix.cmake -DUSE_SYSTEM_NIFTYREG:BOOL=ON -DNIFTYREG_DIR=${NIFTYREG_DIR} -DCMAKE_CXX_FLAGS=-w -DCMAKE_C_FLAGS=-w -DCMAKE_BUILD_TYPE=Release ${SUPERELASTIX_SOURCE_DIR} &&
      make --jobs=4; fi
